name: Release Drafter

on:
  push:
    branches:
      - master

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - name: Stable draft
        uses: release-drafter/release-drafter@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Beta draft
        uses: release-drafter/release-drafter@v7
        with:
          config-name: release-drafter-beta.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
