name: Release

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Set package version
        run: |
          version="${{ github.event.release.tag_name }}"
          version="${version#v}"
          sed -i 's/^__version__ = .*/__version__ = "'"${version}"'"/' custom_components/blitzortung/version.py
          sed -i "s/\"version\": \".*\"/\"version\": \"${version}\"/" custom_components/blitzortung/manifest.json

      - name: Create zipped release package
        shell: bash
        run: |
          cd "${{ github.workspace }}/custom_components/blitzortung"
          zip blitzortung.zip -r ./

      - name: Upload zip to release
        uses: softprops/action-gh-release@v3
        with:
          files: ${{ github.workspace }}/custom_components/blitzortung/blitzortung.zip
